# ╭──────────────────────────────────────────────────────────╮
# │                         Plugins                          │
# ╰──────────────────────────────────────────────────────────╯

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'


run '~/.tmux/plugins/tpm/tpm'

# Themes
set-option -g status-position bottom

set -g status-bg '#1e1e2e'
set -g status-fg '#cdd6f4'

set-option -g status-left ' '
set-option -g status-left-length 0

set -g @host_short "#(echo #{host} | cut -d'.' -f1)"
set -g status-right '#{cpu_fg_color} 󰻠 #{cpu_percentage} #{ram_fg_color} 󰍛 #{ram_percentage}#{?#{==:#{gpu_percentage},No GPU},, #{gpu_fg_color}  #{gpu_percentage}}#[default] - #{host_short}'

set -g pane-border-style 'fg=#45475a'
set -g pane-active-border-style 'fg=#f9e2af'

set -g window-status-style 'fg=#585b70'
set -g window-status-current-style 'fg=#f9e2af'

set -g window-status-format '#I:#W#{?window_zoomed_flag, 󰁌 , }'
set -g window-status-current-format '#I:#W#{?window_zoomed_flag, 󰁌 , }'

# ╭──────────────────────────────────────────────────────────╮
# │                         Options                          │
# ╰──────────────────────────────────────────────────────────╯

# Set true color
set-option -sa terminal-overrides ",xterm*:Tc"
set-option -sa terminal-features ',xterm-kitty:RGB'

set -g mouse on
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set-window-option -g mode-keys vi
set-option -g allow-rename on
set -sg escape-time 0 # more fluent escape key
set -sg repeat-time 0 # more responsive pane switching

# yazi
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

# ╭──────────────────────────────────────────────────────────╮
# │                       Keybindings                        │
# ╰──────────────────────────────────────────────────────────╯

# Set prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Shift Alt vim keys to switch windows
# bind -n M-H previous-window
# bind -n M-L next-window
# bind -n M-S choose-tree -Zs
# bind -n M-W choose-tree

bind -n M-O next-layout

# Visual mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Open panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Open new window in current directory
# bind c new-window -c "#{pane_current_path}"
bind c new-window -c ~

# Resize panes
bind -n S-Up    resize-pane -U 5
bind -n S-Down  resize-pane -D 5
bind -n S-Left  resize-pane -L 5
bind -n S-Right resize-pane -R 5

# Clear scrollback buffer
bind K send-keys "clear"\; send-keys "Enter"\; clear-history

# Reload tmux.conf
bind r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded."
bind s choose-tree -swZ
bind w choose-tree -wZ

bind -n M-S-Left swap-window -t -1\; select-window -t -1
bind -n M-S-Right swap-window -t +1\; select-window -t +1

# go to last prompt
bind-key b copy-mode\;\
           send-keys -X start-of-line\;\
           send-keys -X search-backward "❯"

run-shell ~/.tmux/plugins/tmux-cpu/cpu.tmux
