# include fonts/hack.conf
# include fonts/sourcecodepro.conf
# include fonts/caskaydia.conf
include fonts/jetbrain.conf
# include fonts/firacode.conf
# include fonts/maplemono.conf

symbol_map U+4E00-U+9FFF,U+3400-U+4DBF Maple Mono NF CN
font_size 20                                          
