shell /run/current-system/sw/bin/bash

################################### GENERAL ####################################
allow_remote_control   yes
copy_on_select         yes
click_interval        -1.0

##################################### FONT #####################################
include                font.conf
disable_ligatures      cursor

#################################### WINDOW ####################################
hide_window_decorations        titlebar-only
dynamic_background_opacity     no
# window_padding_width           1 7 1 7
window_padding_width           10
background_opacity             1.9
background_blur                64

#################################### CURSOR ####################################
cursor_blink_interval 0
detect_urls no
mouse_hide_wait 0.5

##################################### TAB ######################################
tab_bar_edge                top
tab_bar_style               powerline
tab_powerline_style         round

################################### KEYBINDINGS ################################
include mappings.conf

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME

#################################### HIGHLIGHT #################################
mark1_foreground #1E1E2E
mark1_background #F38BA8
mark2_foreground #1E1E2E
mark2_background #F9E2AF
map f1 toggle_marker iregex 1 \\bERROR\\b 2 \\bWARNING\\b
