font_family          JetBrainsMono Nerd Font Regular
bold_font            JetBrainsMono Nerd Font Bold
italic_font          JetBrainsMono Nerd Font Italic
bold_italic_font     JetBrainsMono Nerd Font Bold Italic
adjust_line_height 103%
