#!/bin/bash

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors
source "$HOME/.config/sketchybar/icons.sh" # Loads all defined icons

ITEM_DIR="$HOME/.config/sketchybar/items" # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored

FONT="SF Pro" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
PADDINGS=3 # All paddings use this value (icon, label, background)

# Setting up and starting the helper process
# HELPER=git.felix.helper
# killall helper
# cd $HOME/.config/sketchybar/helper && make
# $HOME/.config/sketchybar/helper/helper $HELPER > /dev/null 2>&1 &

# Unload the macOS on screen indicator overlay for volume change
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist > /dev/null 2>&1 &

# Setting up the general bar appearance of the bar
bar=(
  height=32
  color=$BAR_COLOR
  shadow=on
  position=top
  sticky=on
  padding_right=10
  padding_left=10
  corner_radius=0
  y_offset=0
  margin=0
  blur_radius=20
  notch_width=0
)

sketchybar --bar "${bar[@]}"

# Setting up default values
defaults=(
  updates=when_shown
  icon.font="$FONT:Bold:13.0"
  icon.color=$ICON_COLOR
  icon.padding_left=$PADDINGS
  icon.padding_right=$PADDINGS
  label.font="$FONT:Semibold:13.0"
  label.color=$LABEL_COLOR
  label.padding_left=$PADDINGS
  label.padding_right=$PADDINGS
  padding_right=$PADDINGS
  padding_left=$PADDINGS
  background.height=26
  background.corner_radius=5
  popup.background.border_width=2
  popup.background.corner_radius=9
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.blur_radius=20
  popup.background.shadow.drawing=on
)

sketchybar --default "${defaults[@]}"

# Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/yabai_float.sh"
source "$ITEM_DIR/front_app.sh"

# Center
# source "$ITEM_DIR/media.sh"
# Right
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/mail.sh"
source "$ITEM_DIR/things.sh"
source "$ITEM_DIR/messenger.sh"
source "$ITEM_DIR/mattermost.sh"
source "$ITEM_DIR/wechat.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/external_drive.sh"
source "$ITEM_DIR/airpods_status.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/transmission.sh"

sketchybar --add alias "截屏,Item-0" right \
         --set "截屏,Item-0" update_freq=2 \
         --set "截屏,Item-0" click_script="$PLUGIN_DIR/screenshot_click.sh"
sketchybar --add alias "Jellyfin Server,Item-0" right \
         --set "Jellyfin Server,Item-0" update_freq=2


# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded.."
