require('render-markdown').setup {
  sign = { enabled = false },
  quote = {
    repeat_linebreak = true,
  },
  callout = {
    abstract = { raw = '[!ABSTRACT]', rendered = '󰯂 Abstract', highlight = 'RenderMarkdownInfo', category = 'obsidian' },
    summary = { raw = '[!SUMMARY]', rendered = '󰯂 Summary', highlight = 'RenderMarkdownInfo', category = 'obsidian' },
    tldr = { raw = '[!TLDR]', rendered = '󰦩 Tldr', highlight = 'RenderMarkdownInfo', category = 'obsidian' },
    failure = { raw = '[!FAILURE]', rendered = ' Failure', highlight = 'RenderMarkdownError', category = 'obsidian' },
    fail = { raw = '[!FAIL]', rendered = ' Fail', highlight = 'RenderMarkdownError', category = 'obsidian' },
    missing = { raw = '[!MISSING]', rendered = ' Missing', highlight = 'RenderMarkdownError', category = 'obsidian' },
    danger = { raw = '[!DANGER]', rendered = ' Danger', highlight = 'RenderMarkdownError', category = 'obsidian' },
    error = { raw = '[!ERROR]', rendered = ' Error', highlight = 'RenderMarkdownError', category = 'obsidian' },
    bug = { raw = '[!BUG]', rendered = ' Bug', highlight = 'RenderMarkdownError', category = 'obsidian' },
    quote = { raw = '[!QUOTE]', rendered = ' Quote', highlight = 'RenderMarkdownQuote', category = 'obsidian' },
    cite = { raw = '[!CITE]', rendered = ' Cite', highlight = 'RenderMarkdownQuote', category = 'obsidian' },
    todo = { raw = '[!TODO]', rendered = ' Todo', highlight = 'RenderMarkdownInfo', category = 'obsidian' },
    wip = { raw = '[!WIP]', rendered = '󰦖 WIP', highlight = 'RenderMarkdownHint', category = 'obsidian' },
    done = { raw = '[!DONE]', rendered = ' Done', highlight = 'RenderMarkdownSuccess', category = 'obsidian' },
  },
  code = {
    highlight_inline = 'RenderMarkdownCodeInfo',
    render_modes = true,
    position = 'right',
    width = 'block',
    left_margin = 1,
    left_pad = 1,
    right_pad = 1,
    min_width = 80,
    border = 'thin',
    language_icon = true,
    language_name = true,
  },
  heading = {
    render_modes = true,
    border = true,
    border_virtual = true,
    icons = { ' 󰼏 ', ' 󰎨 ', ' 󰼑 ', ' 󰎲 ', ' 󰼓 ', ' 󰎴 ' },
  },
  bullet = { render_modes = true },
  checkbox = {
    unchecked = {
      icon = '󰄱',
      highlight = 'RenderMarkdownCodeFallback',
      scope_highlight = 'RenderMarkdownCodeFallback',
    },
    checked = {
      icon = '󰄵',
      highlight = 'RenderMarkdownUnchecked',
      scope_highlight = 'RenderMarkdownUnchecked',
    },
    custom = {
      question = { raw = '[?]', rendered = '', highlight = 'RenderMarkdownError', scope_highlight = 'RenderMarkdownError' },
      ongoing = { raw = '[>]', rendered = '', highlight = 'RenderMarkdownInfo', scope_highlight = 'RenderMarkdownInfo' },
      canceled = { raw = '[~]', rendered = '', highlight = 'RenderMarkdownCodeFallback', scope_highlight = '@text.strike' },
      important = { raw = '[!]', rendered = '', highlight = 'RenderMarkdownWarn', scope_highlight = 'RenderMarkdownWarn' },
      favorite = { raw = '[^]', rendered = '󰓏', highlight = 'RenderMarkdownMath', scope_highlight = 'RenderMarkdownMath' },
    },
  },
  pipe_table = {
    render_modes = true,
    head = 'RenderMarkdownTableRow',
    alignment_indicator = '─',
    border = {
      '╭',
      '┬',
      '╮',
      '├',
      '┼',
      '┤',
      '╰',
      '┴',
      '╯',
      '│',
      '─',
    },
  },
  link = {
    wiki = { icon = '', highlight = 'RenderMarkdownWikiLink' },
    hyperlink = ' ',
    image = ' ',
    custom = {
      github = { pattern = 'github', icon = ' ' },
      gitlab = { pattern = 'gitlab', icon = '󰮠 ' },
    },
  },
  anti_conceal = {
    ignore = {
      bullet = true,
      indent = true,
      head_background = true,
      head_border = true,
      sign = true,
      virtual_lines = true,
    },
    disabled_modes = { 'n', 'x' },
  },
  win_options = {
    concealcursor = { rendered = 'nvic' },
  },
}
