require('render-markdown').setup {
  debounce = 100,
  render_modes = { 'n', 'c', 't' },
  anti_conceal = {
    enabled = true,
    disabled_modes = { 'n', 'c' },
  },
  file_types = { 'markdown', 'Avante' },
  heading = {
    render_modes = true,
    border = true,
    border_virtual = true,
    icons = { ' 󰼏 ', ' 󰎨 ', ' 󰼑 ', ' 󰎲 ', ' 󰼓 ', ' 󰎴 ' },
  },
  bullet = {
    enabled = true,
    render_modes = true,
    icons = { '◍', '◯', '𜲂', '•' },
    highlight = 'RenderMarkdownBullet',
  },
  link = {
    wiki = { icon = '', highlight = 'RenderMarkdownWikiLink' },
    hyperlink = ' ',
    image = ' ',
    custom = {
      gitlab = { pattern = 'gitlab', icon = ' ' },
      github = { pattern = 'github', icon = '󰮠 ' },
    },
  },
  sign = { enabled = false },
  latex = {
    enabled = true,
    converter = 'latex2text',
    highlight = 'RenderMarkdownMath',
    top_pad = 0,
    bottom_pad = 0,
  },
  checkbox = {
    enabled = true,
    position = 'inline',
    right_pad = 0,
    custom = {
      question = { raw = '[?]', rendered = ' ', highlight = 'RenderMarkdownError' },
      ongoing = { raw = '[>]', rendered = ' ', highlight = 'RenderMarkdownInfo' },
      canceled = { raw = '[~]', rendered = '󰗨 ', highlight = 'ObsidianTilde' },
      important = { raw = '[!]', rendered = ' ', highlight = 'RenderMarkdownWarn' },
      favorite = { raw = '[^]', rendered = ' ', highlight = 'RenderMarkdownMath' },
    },
  },
  pipe_table = {
    render_modes = true,
    head = 'RenderMarkdownTableRow',
    alignment_indicator = '─',
    border = {
      '╭',
      '┬',
      '╮',
      '├',
      '┼',
      '┤',
      '╰',
      '┴',
      '╯',
      '│',
      '─',
    },
  },
  callout = {
    abstract = { raw = '[!ABSTRACT]', rendered = '󰯂 Abstract', highlight = 'RenderMarkdownInfo', category = 'obsidian' },
    summary = { raw = '[!SUMMARY]', rendered = '󰯂 Summary', highlight = 'RenderMarkdownInfo', category = 'obsidian' },
    tldr = { raw = '[!TLDR]', rendered = '󰦩 Tldr', highlight = 'RenderMarkdownInfo', category = 'obsidian' },
    failure = { raw = '[!FAILURE]', rendered = ' Failure', highlight = 'RenderMarkdownError', category = 'obsidian' },
    fail = { raw = '[!FAIL]', rendered = ' Fail', highlight = 'RenderMarkdownError', category = 'obsidian' },
    missing = { raw = '[!MISSING]', rendered = ' Missing', highlight = 'RenderMarkdownError', category = 'obsidian' },
    danger = { raw = '[!DANGER]', rendered = ' Danger', highlight = 'RenderMarkdownError', category = 'obsidian' },
    error = { raw = '[!ERROR]', rendered = ' Error', highlight = 'RenderMarkdownError', category = 'obsidian' },
    bug = { raw = '[!BUG]', rendered = ' Bug', highlight = 'RenderMarkdownError', category = 'obsidian' },
    quote = { raw = '[!QUOTE]', rendered = ' Quote', highlight = 'RenderMarkdownQuote', category = 'obsidian' },
    cite = { raw = '[!CITE]', rendered = ' Cite', highlight = 'RenderMarkdownQuote', category = 'obsidian' },
  },
  quote = {
    enabled = true,
    repeat_linebreak = true,
  },
  code = {
    highlight_inline = 'RenderMarkdownCodeInfo',
    render_modes = true,
    position = 'right',
    width = 'block',
    left_margin = 1,
    left_pad = 1,
    right_pad = 1,
    min_width = 80,
    border = 'thin',
    language_icon = true,
    language_name = true,
  },
}
