#!/bin/bash

function s() {
	kitty +kitten ssh "$@" || ssh "$@"
}

function fssh() {
	local server
	server=$(awk '/^Host / {
    for (i = 2; i <= NF; i++) {
      if ($i !~ /[*?]/) print $i
    }
  }' ~/.ssh/config | sort -u | fzf --prompt="SSH to > ")

	if [[ -n $server ]]; then
		~/dotfiles/scripts/ssh_tmux.sh "$server" &
		exit
	fi
}

function i() {
	filename="${1}"
	if [[ "${filename}" == *.pdf ]]; then
		convert -trim -density 90 "${filename}" PNG:- | kitty +kitten icat
	else
		kitty +kitten icat "${filename}"
	fi
}

function lf() {
	while [ ! -f "$1" ]; do
		echo "Waiting for $1 to be created..."
		sleep 1 # or less like 0.2
	done
	less +F -R "$1"
}

function rl() {
	[ -n "$TMUX" ] && export DISPLAY=$(tmux show-env | sed -n 's/^DISPLAY=//p')
	root -l --web=off "${1}"
}

function rb() {
	[ -n "$TMUX" ] && export DISPLAY=$(tmux show-env | sed -n 's/^DISPLAY=//p')
	rootbrowse "${1}"
}

function xo() {
	[ -n "$TMUX" ] && export DISPLAY=$(tmux show-env | sed -n 's/^DISPLAY=//p')
	xdg-open "${1}" &
}

function rmnfs() {
	if [ -z "$1" ]; then
		echo "Usage: rmnfs <nfs_file>"
		return 1
	fi
	local nfs_file="$1"
	lsof | awk '/\.'$nfs_file'/ {print $2}' | xargs kill -9
}
